### ISSUE TITLE
Validate associations

### ISSUE THREAD

**Issue by yomexzo** [balderdashy/waterline-docs#32] opened 2014-12-13 09:20 UTC
In my case, a message has one or more contacts. I expected association validated when i have
```javascript
// input
var msg = {
	userId: req.user.id,
	dateTime: new Date(),
	sender: data.sender || "",
	message: data.content || "",
	type: "sent",
	contacts: (data.recipients || "").split(/[\s,]+/)
};
// validating
Message.validate(msg, function(err){
	if(err) return reject(err);
	resolve(true);
})

// Association is defined in Message as follows
contacts: {
	collection: 'MessageContact',
	via: 'messageId',
	required: true,
	array: true,
}
```

Snippet above only validates Message and ignores MessageContact(s)

**Comment by devinivy** [comment] 2015-03-23 13:16
I think you'll have more luck with this request if you move it over to the [waterline repo](https://github.com/balderdashy/waterline/issues)!  This sounds like a reasonable enhancement for waterline.

**Comment by dmarcelino** [comment] 2015-04-01 17:08
Closing as duplicate of balderdashy/waterline#224.

**Closed by dmarcelino** 2015-04-01 17:08 UTC
Labels: move issue
